# Deployment do BD
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
      - name: postgre
        image: postgres:13.16
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: fake-shop
        - name: POSTGRES_USER
          value: fake-shop
        - name: POSTGRES_DB
          value: pg1234

---
apiVersion: v1 
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: postgre
  ports:
  - port: 5432
    targetPort: 5432

---
#Deployment da Aplicação
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fakeshop
spec:
  selector:
    matchLabels:
      app: fakeshop
  template:
    metadata:
      labels:
        app: fakeshop
    spec:
      containers:
      - name: fakeshop
        image: rgtrovao/fake-shop:v1
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: postgre
        - name: DB_USER
          value: fakeshop
        - name: DB_PASSWORD
          value: pg1234
        - name: DB_NAME
          value: fakeshop
        - name: FLASK_APP
          value: index.py
---
apiVersion: v1 
kind: Service
metadata:
  name: fakeshop
spec:
  selector:
    app: fakeshop
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer

